-- Seed first 16 philosophy/ethics/morality questions into questions table.
-- Run after schema (e.g. mysql ... align < seed_questions_philosophy.sql)
-- Types: 0=single select, 1=multi-select, 2=scale, 3=free text, 4=ranking, 5=yes/no, 6=other

USE align;

INSERT INTO questions (question_id, question_data) VALUES
(1, '{"id": 1, "question_type": 0, "question": {"number": 1, "text": "Is it more important to do what is right or what is beneficial?"}, "answers": [{"id": 0, "text": "What is right"}, {"id": 1, "text": "What is beneficial"}, {"id": 2, "text": "Depends on the situation"}, {"id": 3, "text": "They are the same"}]'),
(2, '{"id": 2, "question_type": 1, "question": {"number": 2, "text": "Which virtues do you value most? (Select all that apply)"}, "answers": [{"id": 0, "text": "Justice"}, {"id": 1, "text": "Courage"}, {"id": 2, "text": "Compassion"}, {"id": 3, "text": "Honesty"}, {"id": 4, "text": "Wisdom"}]'),
(3, '{"id": 3, "question_type": 2, "question": {"number": 3, "text": "How much do you believe morality is objective (1) vs relative to culture or person (10)?"}, "answers": [{"id": 0, "text": "1 - Fully objective"}, {"id": 1, "text": "3"}, {"id": 2, "text": "5"}, {"id": 3, "text": "7"}, {"id": 4, "text": "10 - Fully relative"}]'),
(4, '{"id": 4, "question_type": 3, "question": {"number": 4, "text": "What does a good life mean to you?"}, "answers": []'),
(5, '{"id": 5, "question_type": 4, "question": {"number": 5, "text": "Rank these as sources of moral guidance (most to least important):"}, "answers": [{"id": 0, "text": "Reason"}, {"id": 1, "text": "Religion or spirituality"}, {"id": 2, "text": "Intuition or gut feeling"}, {"id": 3, "text": "Society and law"}, {"id": 4, "text": "Family and upbringing"}]'),
(6, '{"id": 6, "question_type": 5, "question": {"number": 6, "text": "Do you believe humans have free will?"}, "answers": [{"id": 0, "text": "Yes"}, {"id": 1, "text": "No"}]'),
(7, '{"id": 7, "question_type": 0, "question": {"number": 7, "text": "A trolley is heading toward five people. You can pull a lever to divert it onto a track with one person. Do you pull the lever?"}, "answers": [{"id": 0, "text": "Yes, pull it"}, {"id": 1, "text": "No, do not pull it"}, {"id": 2, "text": "Unsure or it depends"}]'),
(8, '{"id": 8, "question_type": 1, "question": {"number": 8, "text": "Which ethical frameworks resonate with you? (Select all that apply)"}, "answers": [{"id": 0, "text": "Utilitarian (greatest good for greatest number)"}, {"id": 1, "text": "Deontological (duties and rules)"}, {"id": 2, "text": "Virtue ethics (character and flourishing)"}, {"id": 3, "text": "Care ethics (relationships and care)"}, {"id": 4, "text": "Other or none"}]'),
(9, '{"id": 9, "question_type": 2, "question": {"number": 9, "text": "How much should society prioritize the collective good over individual liberty? (1 = individual liberty, 10 = collective good)"}, "answers": [{"id": 0, "text": "1"}, {"id": 1, "text": "3"}, {"id": 2, "text": "5"}, {"id": 3, "text": "7"}, {"id": 4, "text": "10"}]'),
(10, '{"id": 10, "question_type": 0, "question": {"number": 10, "text": "Is it ever acceptable to lie?"}, "answers": [{"id": 0, "text": "Never"}, {"id": 1, "text": "Only to protect someone from harm"}, {"id": 2, "text": "When the truth would cause unnecessary hurt"}, {"id": 3, "text": "Sometimes for convenience"}]'),
(11, '{"id": 11, "question_type": 5, "question": {"number": 11, "text": "Do you believe moral truths exist independently of human beliefs?"}, "answers": [{"id": 0, "text": "Yes"}, {"id": 1, "text": "No"}]'),
(12, '{"id": 12, "question_type": 4, "question": {"number": 12, "text": "Rank what matters most in judging whether an action is right:"}, "answers": [{"id": 0, "text": "Consequences"}, {"id": 1, "text": "Intentions"}, {"id": 2, "text": "Character of the person"}, {"id": 3, "text": "Following the right rules"}]'),
(13, '{"id": 13, "question_type": 0, "question": {"number": 13, "text": "When two moral duties conflict, how do you usually decide?"}, "answers": [{"id": 0, "text": "Choose the greater good"}, {"id": 1, "text": "Follow the stricter rule"}, {"id": 2, "text": "Trust my intuition"}, {"id": 3, "text": "Judge case by case"}]'),
(14, '{"id": 14, "question_type": 1, "question": {"number": 14, "text": "Who do you consider part of your moral community? (Select all that apply)"}, "answers": [{"id": 0, "text": "Family and friends"}, {"id": 1, "text": "My country or culture"}, {"id": 2, "text": "All humans"}, {"id": 3, "text": "Animals"}, {"id": 4, "text": "The environment or future generations"}]'),
(15, '{"id": 15, "question_type": 2, "question": {"number": 15, "text": "How much do you rely on reason vs gut feeling for moral decisions? (1 = reason only, 10 = gut only)"}, "answers": [{"id": 0, "text": "1"}, {"id": 1, "text": "3"}, {"id": 2, "text": "5"}, {"id": 3, "text": "7"}, {"id": 4, "text": "10"}]'),
(16, '{"id": 16, "question_type": 0, "question": {"number": 16, "text": "What do you see as the primary aim of ethics?"}, "answers": [{"id": 0, "text": "Happiness or well-being"}, {"id": 1, "text": "Duty and doing what is right"}, {"id": 2, "text": "Virtue and character"}, {"id": 3, "text": "Freedom and autonomy"}, {"id": 4, "text": "Understanding and wisdom"}]')
ON DUPLICATE KEY UPDATE question_data = VALUES(question_data);
